# Generated by Django 4.2.6 on 2023-11-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='added',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='impact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='insight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='intensity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='likelihood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='pestle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='relevance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
