# Generated by Django 4.2.6 on 2023-11-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarki', '0002_jsondata_added_jsondata_country_jsondata_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='added',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
