# Generated by Django 4.2.6 on 2023-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarki', '0003_alter_jsondata_added_alter_jsondata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='added',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='published',
            field=models.TextField(blank=True, null=True),
        ),
    ]
