# Generated by Django 4.2.6 on 2023-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarki', '0004_alter_jsondata_added_alter_jsondata_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='country',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='impact',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='insight',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='pestle',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='region',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='sector',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='source',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='title',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='topic',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='url',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
