# Generated by Django 4.2.6 on 2023-11-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarki', '0005_alter_jsondata_country_alter_jsondata_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='insight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='pestle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='sector',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
